Org extension create
ELEVATE-Project/mentoring pull request #500
Opened 2024-01-21 17:41 UTC by joffinjoy

2024-01-22 03:36 UTC, aks30 requested changes
Reviewed on 22 Jan

2024-01-22 03:36 UTC, aks30 commented on src/database/queries/organisationExtension.js
> +			const newOrgExtension = await OrganizationExtension.create(data, options)
@joffinjoy why is it not consistently  camel case OrganizationExtension => organizationExtension

2024-02-01 06:23 UTC, rakeshSgr commented on src/services/organization.js
> +			const extensionData = {
@joffinjoy can we use the eventBody Object to upsert, instead of accessing and storing the fields

2024-02-01 06:25 UTC, rakeshSgr commented on src/helpers/eventListnerRouter.js
> +		switch (eventBody.eventType) {
@joffinjoy for new event type we need to upset this ?

2024-02-01 06:36 UTC, merged