Bulk Upload Session Enhancement
ELEVATE-Project/mentoring pull request #749
Opened 2024-05-30 15:02 UTC by sumanvpacewisdom

2024-05-31 07:35 UTC, nevil-mathew requested changes

2024-05-31 07:35 UTC, nevil-mathew commented on src/services/sessionInvite.js
> +					if (session.mentees.length === 0) {
Remove this as we're already checking this in the above function.

2024-05-31 07:35 UTC, nevil-mathew commented on src/services/sessionInvite.js
> +			let entityTypes = await entityTypeQueries.findUserEntityTypesAndEntities({
Pull this out of the functions, since we're using the same data in multiple places.

2024-05-31 07:35 UTC, nevil-mathew commented on src/constants/common.js
>  		WHATSAPP_MEET: 'WhatsApp',
remove meet from the above keys and add "LABEL"

2024-06-03 06:57 UTC, nevil-mathew commented on src/services/sessionInvite.js
> +					if (meetingName.includes(common.MEETING_VALUES.ZOOM_VALUE)) {
Can we refactor the below if cases?

2024-06-04 05:10 UTC, rakeshSgr commented on src/locales/en.json
> +	"BELOW_MINIMUM_SESSION_TIME": "End time should be atleast 30 minutes after start time.",
@sumanvpacewisdom it is not a meaning full key " BELOW_MINIMUM_SESSION_TIME"

2024-06-04 05:12 UTC, rakeshSgr commented on src/locales/en.json
> +	"SESSION_CREATION_LIMIT_EXCEDED_FOR_GIVEN_MENTOR": "The selected mentor has a session scheduled at the specified time."
@sumanvpacewisdom change to MENTOR_SESSION_CREATION_LIMIT

2024-06-04 05:12 UTC, sumanvpacewisdom commented on src/locales/en.json
> +	"BELOW_MINIMUM_SESSION_TIME": "End time should be atleast 30 minutes after start time.",
@rakeshSgr This was given by products team. I have updated

2024-06-04 06:34 UTC, nevil-mathew commented on src/services/sessionInvite.js
> +				const zoomMeetingRegex = /https:\/\/(?:meet|call|us\d{2}web|zoom)\.(\w+)\.us\/j\/(\d+)\?/
Move these to constants

2024-06-04 06:35 UTC, nevil-mathew approved these changes

2024-06-04 06:36 UTC, nevil-mathew approved these changes

2024-06-04 06:50 UTC, merged