commented changes
ELEVATE-Project/mentoring pull request #798
Opened 2024-06-27 05:19 UTC by sumanvpacewisdom

2024-06-27 05:27 UTC, nevil-mathew requested changes

2024-06-27 05:27 UTC, nevil-mathew commented on src/validators/v1/default-rule.js
> +				.optional()
Remove checkBody for read, only id is needed

2024-06-27 05:27 UTC, nevil-mathew commented on src/validators/v1/default-rule.js
> +				.optional()
and id is optional

2024-06-27 05:27 UTC, nevil-mathew commented on src/validators/v1/default-rule.js
> +				.isIn(['=', '!=', '>', '<', '>=', '<='])
Update this to words, eg: "equals"

2024-06-27 05:27 UTC, nevil-mathew commented on src/validators/v1/default-rule.js
req.checkBody('role_config').isObject()

is .isObject() valid?

2024-06-27 05:27 UTC, nevil-mathew commented on src/validators/v1/default-rule.js
and add isIn to type as well, with allowed values in session, and mentor

2024-07-01 07:33 UTC, sumanvpacewisdom commented
@nevil-mathew Updated the commented changes , please review and let me know

2024-07-02 12:36 UTC, nevil-mathew commented on src/validators/v1/default-rule.js
> +				)
It should match from these:
	['equals', '='],
	['notEquals', '!='],
	['contains', '@>'],
	['containedBy', '<@'],
	['overlap', '&&'],
	['lessThan', '<'],
	['greaterThan', '>'],
	['lessThanOrEqual', '<='],
	['greaterThanOrEqual', '>='],
so please remove the spaces in between.

2024-07-02 14:22 UTC, nevil-mathew approved these changes

2024-07-02 14:22 UTC, merged